# Generated by Django 4.1.2 on 2022-10-08 05:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes', '0002_anhsanpham_san_pham_alter_sanpham_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anhsanpham',
            name='san_pham',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Shoes.sanpham'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='danh_muc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='Shoes.danhmuc'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
