# Generated by Django 4.1 on 2022-11-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes', '0003_alter_anhsanpham_san_pham_alter_sanpham_danh_muc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binhluan',
            name='nguoi_tao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='Shoes.sanpham'),
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cong_thanh_toan', models.CharField(max_length=50)),
                ('ngay', models.DateTimeField(auto_now_add=True)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ThanhToan',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_sua', models.DateTimeField(auto_now=True)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thanh_toan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shoes.thanhtoan')),
            ],
            options={
                'db_table': 'DonHang',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_sua', models.DateTimeField(auto_now=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('gia_tri', models.PositiveSmallIntegerField(default=0)),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shoes.sanpham')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('gia', models.CharField(max_length=20)),
                ('don_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shoes.donhang')),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shoes.sanpham')),
            ],
            options={
                'db_table': 'ChiTietDonHang',
            },
        ),
    ]
