# Generated by Django 4.1 on 2022-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes', '0004_alter_binhluan_nguoi_tao_alter_binhluan_san_pham_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='danhgia',
            table='DanhGia',
        ),
    ]
